### PR TITLE
Frontend add "Progress" button for dashboard in 9 languages

### LINKED ISSUE #7: Create a new tab for the document management dashboard
Acceptance Criteria: Admins should be able to access a new page with the dashboard displaying documents in three status columns.
Effort: Low
Dependencies: None

### PR DESCRIPTION
**Pull request by nathaliejeans**
Frontend changes for Issue #7 
New tab for page called Progress to link to our dashboard
Translates to Chinese, French, Russian, English, Polish, Spanish, Italian, Greek, etc.

### CODE REVIEW

**Review by zz0418 — CHANGES_REQUESTED** [review]
Natalie I think you changed another field for Greek instead of adding a new field

**Comment by nathaliejeans** [comment]
> Natalie I think you changed another field for Greek instead of adding a new field

Thanks for catching that, I just fixed it!

**Review by zz0418 — APPROVED** [review]
LGTM

**Review by fionaaac — COMMENTED** [review]
LGTM

**Pull request merged**
