### PR TITLE
Updated the rest endpoints and Document/DocumentDto/DocumentDao java models

### LINKED ISSUE #6: Add new progress attributes to document.java model
**Effort required:** Medium time commitment
**Acceptance Criteria:** Documents should allow user to add a document with specified progress
**Dependencies:** Fields should exist in database (Issue #2)

### LINKED ISSUE #13: Create/update REST endpoint for document progress
Acceptance Criteria: After a user clicks a button, a request should be sent to update the document in the database
Effort: Medium
Dependencies: Database and model updates should be completed

### PR DESCRIPTION
**Pull request by phi-h-nguyen**
for issues #6 and #13

### CODE REVIEW

**Review by zz0418 — APPROVED** [review]
LGTM

**Review by fionaaac — CHANGES_REQUESTED** [review]
Current changes result in a status 500 error when trying to add a document. Please check and fix the PUT endpoint.

**Review by zeptose — APPROVED** [review]
LGTM

**Review by fionaaac — APPROVED** [review]
LGTM

**Comment by nathaliejeans** [comment]
@phi-h-nguyen @fionaaac @zeptose @zz0418 Just updated type of progress from integer to string. Please review and let me know if changes are good

**Pull request merged**
